{{- if .Values.cluster.enabled -}}
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: {{ template "rook-resources.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  dataDirHostPath: {{ .Values.cluster.dataDirHostPath }}
  hostNetwork: {{ .Values.cluster.hostNetwork }}
  monCount: {{ .Values.cluster.monCount }}
  # placement:
  #   mgr:
  #     {{ .Values.cluster.placement.mgr }}
  #   mon:
  #     {{ .Values.cluster.placement.mon }}
  #   osd:
  #     {{ .Values.cluster.placement.osd }}
  #   all:
  #     {{ .Values.cluster.placement.all }}
  storage:
    useAllNodes: {{ .Values.cluster.storage.useAllNodes }}
    useAllDevices: {{ .Values.cluster.storage.useAllDevices }}
    deviceFilter: {{ .Values.cluster.storage.deviceFilter }}
    metadataDevice:
    directories:
    storeConfig:
      storeType: {{ .Values.cluster.storage.storeConfig.storeType }}
      databaseSizeMB: {{ .Values.cluster.storage.storeConfig.databaseSizeMB }}
      journalSizeMB: {{ .Values.cluster.storage.storeConfig.journalSizeMB }}
    nodes: {{ .Values.cluster.storage.nodes }}
  resources:
    mgr:
      requests:
          cpu: "{{ .Values.cluster.resources.mgr.requests.cpu }}"
          memory: "{{ .Values.cluster.resources.mgr.requests.memory }}"
      limits:
          cpu: "{{ .Values.cluster.resources.mgr.limits.cpu }}"
          memory: "{{ .Values.cluster.resources.mgr.limits.memory }}"
    mon:
      requests:
          cpu: "{{ .Values.cluster.resources.mon.requests.cpu }}"
          memory: "{{ .Values.cluster.resources.mon.requests.memory }}"
      limits:
          cpu: "{{ .Values.cluster.resources.mon.limits.cpu }}"
          memory: "{{ .Values.cluster.resources.mon.limits.memory }}"
    osd:
      requests:
          cpu: "{{ .Values.cluster.resources.osd.requests.cpu }}"
          memory: "{{ .Values.cluster.resources.osd.requests.memory }}"
      limits:
          cpu: "{{ .Values.cluster.resources.osd.limits.cpu }}"
          memory: "{{ .Values.cluster.resources.osd.limits.memory }}"
{{- end }}
